workspace(name = "t2")

local_repository(
	name = "t1",
	path = "../t1",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
        name = "com_github_grpc_grpc",
        urls = [
                "https://github.com/grpc/grpc/archive/refs/tags/v1.39.0.tar.gz",
        ],
        strip_prefix = "grpc-1.39.0",
        sha256 = "b16992aa1c949c10d5d5ce2a62f9d99fa7de77da2943e643fb66dcaf075826d6",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
